In [1]:
import pandas as pd
import numpy as np

import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.model_selection import train_test_split

from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import StandardScaler

from sklearn.linear_model import LogisticRegression

from sklearn.metrics import accuracy_score
from sklearn.metrics import confusion_matrix
from sklearn.metrics import classification_report
from sklearn.metrics import precision_score
from sklearn.metrics import recall_score
from sklearn.metrics import f1_score

In [2]:
df = pd.read_csv("AirQualityUCI.csv")
df.head()

                                                                                                            Date;Time;CO(GT);PT08.S1(CO);NMHC(GT);C6H6(GT);PT08.S2(NMHC);NOx(GT);PT08.S3(NOx);NO2(GT);PT08.S4(NO2);PT08.S5(O3);T;RH;AH;;
10/03/2004;18.00.00;2            6;1360;150;11                 9;1046;166;1056;113;1692;1268;13 6;48 9;0                                                7578;;
10/03/2004;19.00.00;2;1292;112;9 4;955;103;1174;92;1559;972;13 3;47                             7;0  7255;;                                                NaN
10/03/2004;20.00.00;2            2;1402;88;9                   0;939;131;1140;114;1555;1074;11  9;54 0;0                                                7502;;
10/03/2004;21.00.00;2            2;1376;80;9                   2;948;172;1092;122;1584;1203;11  0;60 0;0                                                7867;;
10/03/2004;22.00.00;1            6;1272;51;6                   5;836;131;1205;116;1490;1110;11  2;59 6;0                                                7888;;

In [3]:
# Display Dataset
print(df)

                                                                                                            Date;Time;CO(GT);PT08.S1(CO);NMHC(GT);C6H6(GT);PT08.S2(NMHC);NOx(GT);PT08.S3(NOx);NO2(GT);PT08.S4(NO2);PT08.S5(O3);T;RH;AH;;
10/03/2004;18.00.00;2            6;1360;150;11                 9;1046;166;1056;113;1692;1268;13 6;48 9;0                                                7578;;
10/03/2004;19.00.00;2;1292;112;9 4;955;103;1174;92;1559;972;13 3;47                             7;0  7255;;                                                NaN
10/03/2004;20.00.00;2            2;1402;88;9                   0;939;131;1140;114;1555;1074;11  9;54 0;0                                                7502;;
10/03/2004;21.00.00;2            2;1376;80;9                   2;948;172;1092;122;1584;1203;11  0;60 0;0                                                7867;;
10/03/2004;22.00.00;1            6;1272;51;6                   5;836;131;1205;116;1490;1110;11  2;59 6;0                                                7888;;
...                                                                                                                                                        ...
;;;;;;;;;;;;;;;;                 NaN                           NaN                              NaN  NaN                                                   NaN
                                                                                                     NaN                                                   NaN
                                                                                                     NaN                                                   NaN
                                                                                                     NaN                                                   NaN
                                                                                                     NaN                                                   NaN

[9471 rows x 1 columns]

In [4]:
# First Five Rows
df.head()

                                                                                                            Date;Time;CO(GT);PT08.S1(CO);NMHC(GT);C6H6(GT);PT08.S2(NMHC);NOx(GT);PT08.S3(NOx);NO2(GT);PT08.S4(NO2);PT08.S5(O3);T;RH;AH;;
10/03/2004;18.00.00;2            6;1360;150;11                 9;1046;166;1056;113;1692;1268;13 6;48 9;0                                                7578;;
10/03/2004;19.00.00;2;1292;112;9 4;955;103;1174;92;1559;972;13 3;47                             7;0  7255;;                                                NaN
10/03/2004;20.00.00;2            2;1402;88;9                   0;939;131;1140;114;1555;1074;11  9;54 0;0                                                7502;;
10/03/2004;21.00.00;2            2;1376;80;9                   2;948;172;1092;122;1584;1203;11  0;60 0;0                                                7867;;
10/03/2004;22.00.00;1            6;1272;51;6                   5;836;131;1205;116;1490;1110;11  2;59 6;0                                                7888;;

In [5]:
# Last Five Rows
df.tail()

                                 Date;Time;CO(GT);PT08.S1(CO);NMHC(GT);C6H6(GT);PT08.S2(NMHC);NOx(GT);PT08.S3(NOx);NO2(GT);PT08.S4(NO2);PT08.S5(O3);T;RH;AH;;
;;;;;;;;;;;;;;;; NaN NaN NaN NaN                                                NaN
                             NaN                                                NaN
                             NaN                                                NaN
                             NaN                                                NaN
                             NaN                                                NaN

In [6]:
# Shape of Dataset
print("Shape of Dataset :", df.shape)

Shape of Dataset : (9471, 1)

In [7]:

# Column Names
print(df.columns)

Index(['Date;Time;CO(GT);PT08.S1(CO);NMHC(GT);C6H6(GT);PT08.S2(NMHC);NOx(GT);PT08.S3(NOx);NO2(GT);PT08.S4(NO2);PT08.S5(O3);T;RH;AH;;'], dtype='object')

In [8]:

# Dataset Information
df.info()

<class 'pandas.core.frame.DataFrame'>
MultiIndex: 9471 entries, ('10/03/2004;18.00.00;2', '6;1360;150;11', '9;1046;166;1056;113;1692;1268;13', '6;48', '9;0') to (';;;;;;;;;;;;;;;;', nan, nan, nan, nan)
Data columns (total 1 columns):
 #   Column                                                                                                                        Non-Null Count  Dtype
---  ------                                                                                                                        --------------  -----
 0   Date;Time;CO(GT);PT08.S1(CO);NMHC(GT);C6H6(GT);PT08.S2(NMHC);NOx(GT);PT08.S3(NOx);NO2(GT);PT08.S4(NO2);PT08.S5(O3);T;RH;AH;;  6915 non-null   object
dtypes: object(1)
memory usage: 1.2+ MB

In [10]:
 #Data Types
print(df.dtypes)

Date;Time;CO(GT);PT08.S1(CO);NMHC(GT);C6H6(GT);PT08.S2(NMHC);NOx(GT);PT08.S3(NOx);NO2(GT);PT08.S4(NO2);PT08.S5(O3);T;RH;AH;;    object
dtype: object

In [11]:
# Statistical Summary
df.describe()

       Date;Time;CO(GT);PT08.S1(CO);NMHC(GT);C6H6(GT);PT08.S2(NMHC);NOx(GT);PT08.S3(NOx);NO2(GT);PT08.S4(NO2);PT08.S5(O3);T;RH;AH;;
count                                                6915
unique                                               4941
top                                                7487;;
freq                                                    6

In [12]:
# Check Missing Values
df.isnull().sum()

Date;Time;CO(GT);PT08.S1(CO);NMHC(GT);C6H6(GT);PT08.S2(NMHC);NOx(GT);PT08.S3(NOx);NO2(GT);PT08.S4(NO2);PT08.S5(O3);T;RH;AH;;    2556
dtype: int64

In [13]:

# Total Missing Values
print("Total Missing Values :", df.isnull().sum().sum())

Total Missing Values : 2556

In [14]:

# Duplicate Rows
print("Duplicate Rows :", df.duplicated().sum())

Duplicate Rows : 4529

In [15]:
# Remove Duplicate Rows
df = df.drop_duplicates()

In [16]:
# Check Unique Values
for column in df.columns:
    print(column)
    print(df[column].nunique())
    print("-"*40)

Date;Time;CO(GT);PT08.S1(CO);NMHC(GT);C6H6(GT);PT08.S2(NMHC);NOx(GT);PT08.S3(NOx);NO2(GT);PT08.S4(NO2);PT08.S5(O3);T;RH;AH;;
4941
----------------------------------------

In [17]:

# Display Random Records
df.sample(10)

                                                                              Date;Time;CO(GT);PT08.S1(CO);NMHC(GT);C6H6(GT);PT08.S2(NMHC);NOx(GT);PT08.S3(NOx);NO2(GT);PT08.S4(NO2);PT08.S5(O3);T;RH;AH;;
29/03/2005;16.00.00;2 7;1234;-200;12 3;1060;349;509;153;1504;1251;18 3;54 8;1                                             1403;;
24/03/2004;06.00.00;0 8;954;32;1     7;561;43;1496;57;1255;612;10    8;57 2;0                                             7382;;
27/03/2005;07.00.00;1 1;1082;-200;4  2;720;144;697;76;1297;960;15    6;67 7;1                                             1911;;
18/03/2005;15.00.00;2 3;1264;-200;12 9;1081;318;555;177;1323;951;25  9;21 9;0                                             7209;;
28/05/2004;16.00.00;1 7;1039;-200;12 2;1055;131;966;117;1590;845;28  0;23 2;0                                             8613;;
14/07/2004;16.00.00;2 1;934;-200;11  7;1041;203;865;136;1496;936;32  3;16 7;0                                             7946;;
27/12/2004;10.00.00;1 9;1131;-200;8  6;926;288;684;127;1324;1036;12  9;63 2;0                                             9335;;
06/07/2004;18.00.00;4 4;1298;-200;25 0;1430;317;632;194;1946;2475;37 9;13 9;0                                             9015;;
22/09/2004;22.00.00;2 1;1110;-200;11 5;1032;183;702;98;1650;1002;22  5;62 6;1                                             6883;;
01/04/2005;05.00.00;0 5;868;-200;1   4;535;88;1136;66;944;395;13     5;50 6;0                                             7783;;

In [18]:

# Correlation Matrix
df.corr(numeric_only=True)

Empty DataFrame
Columns: []
Index: []